char skills[22][40] = {
    "Programming: C, C Sharp, Python,",
    "Java, JavaScript, PHP",
    "",
    "Database: SQL, SQLite DB Browser",
    "",
    "Web: CSS, JSON, AJAX, CGI, Apache",
    "",
    "Cloud systems: Azure",
    "",
    "IDEs: Visual Studio, Android Studio,",
    "IntelliJ, PyCharm, VS Code",
    "",
    "Tools: Git, Virtualbox, SSH, RDP, ",
    "PowerShell, bash, Blender",
    "",
    "Quality: Test automation, test ",
    "development, debugging",
    "",
    "Language: Japanese (JLPT N3)",
    "",
    "Other: Data Structures, Algorithms,",
    "Lambda Functions"
};
